name: webdev
channels:
  - anaconda
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - alembic=1.16.4
  - annotated-types=0.6.0
  - ansi2html=1.9.1
  - anyio=4.7.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - bcrypt=4.3.0
  - blas=1.0
  - blinker=1.9.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.7.14
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.8
  - cryptography=45.0.5
  - cyrus-sasl=2.1.28
  - dash=3.1.1
  - dash-bootstrap-components=2.0.3
  - dnspython=2.4.2
  - ecdsa=0.19.0
  - email-validator=2.2.0
  - email_validator=2.2.0
  - expat=2.7.1
  - fastapi=0.116.1
  - fastapi-cli=0.0.8
  - fastapi-core=0.116.1
  - flask=3.0.3
  - flask-compress=1.17
  - greenlet=3.1.1
  - h11=0.16.0
  - httpcore=1.0.9
  - httptools=0.6.4
  - httpx=0.28.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - mako=1.2.3
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - mdurl=0.1.0
  - narwhals=1.31.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.11.0
  - numpy=2.3.1
  - numpy-base=2.3.1
  - openldap=2.6.4
  - openssl=3.0.17
  - packaging=24.2
  - pandas=2.3.1
  - passlib=1.7.4
  - pip=25.1
  - plotly=6.0.1
  - psycopg2=2.9.10
  - pyasn1=0.6.1
  - pycparser=2.21
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pydantic-settings=2.10.1
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.13.5
  - python-dateutil=2.9.0post0
  - python-dotenv=1.1.0
  - python-jose=3.5.0
  - python-multipart=0.0.20
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.4
  - retrying=1.3.3
  - rich=13.9.4
  - rich-toolkit=0.14.9
  - rsa=4.7.2
  - setuptools=72.1.0
  - shellingham=1.5.0
  - six=1.17.0
  - sniffio=1.3.0
  - sqlalchemy=2.0.42
  - sqlite=3.50.2
  - starlette=0.46.2
  - tk=8.6.14
  - tomli=2.2.1
  - typer=0.16.0
  - typer-slim=0.16.0
  - typer-slim-standard=0.16.0
  - typing-extensions=4.12.2
  - typing-inspection=0.4.0
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.5.0
  - uvicorn=0.35.0
  - uvicorn-standard=0.35.0
  - uvloop=0.21.0
  - watchfiles=0.24.0
  - websockets=15.0.1
  - werkzeug=3.0.6
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
#prefix: /opt/anaconda3/envs/webdev
