name: Build and Deploy Code (CI/CD)

# What triggers the workflow to run?
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - main

# Create a job
jobs:
  job1:
    runs-on: ubuntu-latest

    # Steps to run in the job
    steps:
      - name: Pulling git repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies from requirements.txt
        run: |
          pip install -r requirements.txt
