name: Build and Deploy Code (CI/CD)

# What triggers the workflow to run?
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - main

# Create a job
jobs:
  job1:
    environment:
      name: Configure Testing
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}} # This is the arbitrary hostname of the PostgreSQL database server
      DATABASE_PORT: ${{secrets.DATABASE_PORT}} # This is the port number of the PostgreSQL database server
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}} # This is the password for the PostgreSQL database
      DATABASE_NAME: ${{secrets.DATABASE_NAME}} # This is the name of the PostgreSQL database
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}} # This is the username for the PostgreSQL database
      SECRET_KEY: ${{secrets.SECRET_KEY}} # This is the secret key used for signing tokens
      ALGORITHM: ${{secrets.ALGORITHM}} # This is the algorithm used for signing tokens
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}} # This is the

    services:
      postgres: # creating service named 'postgres'
        image: postgres
        env:
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}_test # This is the name of the PostgreSQL database
          POSTGRES_USER: ${{secrets.DATABASE_USERNAME}} # This is the username for the PostgreSQL database
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}} # This is the password for the PostgreSQL database
        ports:
          - 5432:5432 # This is the port number
        options: >- # This is the options for the PostgreSQL database
          --health-cmd pg_isready
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    runs-on: ubuntu-latest
    # Steps to run in the job
    steps:
      - name: Pulling git repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          auto-activate-base: false
          activate-environment: myenv
          channels: conda-forge
          packages: pytest
      - name: Verify conda environment
        run: conda info --envs
      - name: Test using pytest
        run: |
          pytest
